// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: notification.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendUserPushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Data          map[string]string      `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendUserPushRequest) Reset() {
	*x = SendUserPushRequest{}
	mi := &file_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendUserPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendUserPushRequest) ProtoMessage() {}

func (x *SendUserPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendUserPushRequest.ProtoReflect.Descriptor instead.
func (*SendUserPushRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

func (x *SendUserPushRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SendUserPushRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendUserPushRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SendUserPushRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendUserPushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SentCount     int32                  `protobuf:"varint,2,opt,name=sent_count,json=sentCount,proto3" json:"sent_count,omitempty"`
	FailedTokens  []string               `protobuf:"bytes,3,rep,name=failed_tokens,json=failedTokens,proto3" json:"failed_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendUserPushResponse) Reset() {
	*x = SendUserPushResponse{}
	mi := &file_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendUserPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendUserPushResponse) ProtoMessage() {}

func (x *SendUserPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendUserPushResponse.ProtoReflect.Descriptor instead.
func (*SendUserPushResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SendUserPushResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendUserPushResponse) GetSentCount() int32 {
	if x != nil {
		return x.SentCount
	}
	return 0
}

func (x *SendUserPushResponse) GetFailedTokens() []string {
	if x != nil {
		return x.FailedTokens
	}
	return nil
}

var File_notification_proto protoreflect.FileDescriptor

const file_notification_proto_rawDesc = "" +
	"\n" +
	"\x12notification.proto\x12\x18ceramicraft.notification\"\xde\x01\n" +
	"\x13SendUserPushRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12K\n" +
	"\x04data\x18\x04 \x03(\v27.ceramicraft.notification.SendUserPushRequest.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"t\n" +
	"\x14SendUserPushResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"sent_count\x18\x02 \x01(\x05R\tsentCount\x12#\n" +
	"\rfailed_tokens\x18\x03 \x03(\tR\ffailedTokens2\x84\x01\n" +
	"\x13NotificationService\x12m\n" +
	"\fSendUserPush\x12-.ceramicraft.notification.SendUserPushRequest\x1a..ceramicraft.notification.SendUserPushResponseB5Z3github.com/sw5005-sus/ceramicraft-push-client/pb;pbb\x06proto3"

var (
	file_notification_proto_rawDescOnce sync.Once
	file_notification_proto_rawDescData []byte
)

func file_notification_proto_rawDescGZIP() []byte {
	file_notification_proto_rawDescOnce.Do(func() {
		file_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)))
	})
	return file_notification_proto_rawDescData
}

var file_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_notification_proto_goTypes = []any{
	(*SendUserPushRequest)(nil),  // 0: ceramicraft.notification.SendUserPushRequest
	(*SendUserPushResponse)(nil), // 1: ceramicraft.notification.SendUserPushResponse
	nil,                          // 2: ceramicraft.notification.SendUserPushRequest.DataEntry
}
var file_notification_proto_depIdxs = []int32{
	2, // 0: ceramicraft.notification.SendUserPushRequest.data:type_name -> ceramicraft.notification.SendUserPushRequest.DataEntry
	0, // 1: ceramicraft.notification.NotificationService.SendUserPush:input_type -> ceramicraft.notification.SendUserPushRequest
	1, // 2: ceramicraft.notification.NotificationService.SendUserPush:output_type -> ceramicraft.notification.SendUserPushResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_notification_proto_init() }
func file_notification_proto_init() {
	if File_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_proto_goTypes,
		DependencyIndexes: file_notification_proto_depIdxs,
		MessageInfos:      file_notification_proto_msgTypes,
	}.Build()
	File_notification_proto = out.File
	file_notification_proto_goTypes = nil
	file_notification_proto_depIdxs = nil
}
